### ISSUE TITLE
[BUG] Fishing Loots not working properly.

### ISSUE THREAD

**Issue by spiker5032** [PluginBugs/Issues-ItemsAdder#1130]
Describe the bug
Fishing loots are global.
If I set some fish to only be catchable in ICE_SPIKE Biomes I can catch them in DESERT

To Reproduce
Set Biomes for fish spawn

Expected behavior
Fish would only come from the expected biome

Screenshots
[Bug In Video](https://www.youtube.com/watch?v=L-dwIOMpkvM)

Here is the YML for the Fish I caught in the video. The fish was caught in a DESERT_LAKES biome but it is a Ice fish
    lootsole:
      biomes:
        - ICE_SPIKES
        - SNOWY_BEACH
        - SNOWY_MOUNTAINS
        - SNOWY_TAIGA
        - SNOWY_TAIGA_HILLS
        - SNOWY_TAIGA_MOUNTAINS
        - SNOWY_TUNDRA
        - FROZEN_RIVER

Server version: 1.17.2
Client version: 1.17.2 Fabric

ItemsAdder version: 2.4.11
LoneLibs version: 1.0.14
ProtocolLib version: 4.7.0

## Todo
- [x] Fix biomes not working correctly in recipes rules
- [x] Fix loots not reloaded correctly when using /iareload after 10 minutes of server usage
- [x] Fix biomes lore being too long

**Comment by spiker5032** [comment]
Id also like to add that LootTables only update upon server restart.

**Comment by LoneDev6** [comment]
Thanks a lot for the report, this will be addressed in the next days

**Comment by spiker5032** [comment]
> Thanks a lot for the report, this will be addressed in the next days

Id also like to say that /iareload does not work after the server has been open for more then 10 Mins when making new recipes.

Meaning you cant make new recipes/update old ones without restarting the server.

**Comment by LoneDev6** [comment]
Thanks, this will be addressed in the next release
