### ISSUE TITLE
Idea for storage type Furnitures (EPIC BackPacks compatibility)

### ISSUE THREAD

**Issue by SirGlozz** [PluginBugs/Issues-ItemsAdder#1449]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Glozz#9549

### Describe the solution you'd like

Add a custom furniture behaviour to open backpack on a furniture when right clicking, i noticed if you set a furniture to backpack in your EPIC backpacks plugin, the items inside the backpack get stored in the backpack item despite its a furniture. If you break the backpack furniture, the items still inside when the furniture drops (it works like a shulker box)

### Is your feature request related to a problem?

It's not related to a problem, only a nice feature that would be useful  to make interesting furnitures such as fridges, trash cans or custom chests, we can store items inside furnitures, but would be nice to open backpacks through placed furniture.

### Describe alternatives you've considered

Add furniture behaviour to execute open backpack event on the placed furniture (worn as backpack obviously), and use right click to open.
Example:
```
    behaviours:
      furniture:
        open_backpack: true
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          walls: false
          ceiling: false
          floor: true
```

### Additional context

![2022-01-23_20 46 07](https://user-images.githubusercontent.com/77519944/150703495-1c5e7488-d94f-4b8c-8d94-61ee0218d925.png)
![2022-01-23_20 46 21](https://user-images.githubusercontent.com/77519944/150703498-10f4e86d-5730-4317-91b2-c01631508834.png)

**Comment by LoneDev6** [comment]
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/777
