### ISSUE TITLE
[ItemsAdder] Added the possibility of texturing old minecraft meta 

### ISSUE THREAD

**Issue by NoHere32** [PluginBugs/Issues-ItemsAdder#2656]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

NoHere#7644

### Describe the solution you'd like

In minecraft other times several blocks had 16 block meta (0 - 15) e.g.: Deadbrush = 31:(0, 3 - 15) 

31:0 being the version of the basic item it will remain to the creator of pack to texturize it or not but the others it can be cool.

### Is your feature request related to a problem?

At the moment I am using the age of the twisted_vines in order to texturize but this means that I will have to lock this culture to my players.

### Describe alternatives you've considered

At the moment I am using the age of the twisted_vines in order to texturize but this means that I will have to lock this culture to my players.

### Additional context

it would allow to add custom plants (custom geo)

**Comment by LoneDev6** [comment]
I don't understand what you are requesting.
The "block meta" you're referring to doesn't exists anymore in Minecraft and there is no way to bring it back.

**Comment by NoHere32** [comment]
https://youtu.be/Nm6ieUESd34
Hello, the video is being uploaded

**Comment by NoHere32** [comment]
No, twisted-vines are blocks that use age. I'm talking about taking the old meta that's still accessible and not used by Minecraft.

If the idea of twisted-vines is simpler and makes it possible not to lock resources to players on a server and (perhaps it's possible to deactivate the ladder function of the vine, then if the second part isn't possible at all, too bad, it won't be bad enough not to lock resources to players).

**Comment by LoneDev6** [comment]
This is basically what I said before.
> implement custom blocks using `twisted_vines` as base for the custom block

Obviously without using blockstates which appear ingame.
Anyway I'll have to make some research to check if there is any downside, the main one is performance as vines and similar blocks are known to have a lot of physic updates which need to be cancelled.
